### ISSUE TITLE
Detector State 0 page shows incorrect enabled triggers

### ISSUE THREAD

**Issue by estherturner** [snoplus/minard#69]
The detector state /0 page shows the wrong set of enabled triggers (and the thresholds for those, rather than the correct set of enabled triggers). I've attached screenshots. 
![screen shot 2017-05-29 at 15 27 42](https://cloud.githubusercontent.com/assets/14888026/26560315/71e50124-4483-11e7-8fad-7f23a19c8eab.png)
![screen shot 2017-05-29 at 15 28 08](https://cloud.githubusercontent.com/assets/14888026/26560318/7a57c198-4483-11e7-8969-7523cf419f1c.png)

**Comment by tlatorre-uchicago** [comment]
This is the second time this has happened, so it's probably a real issue that needs to be resolved. Somehow, the timed event which is supposed to save the mtc server state isn't getting run. My only current hypothesis is that it's due to bad RAM on the SBC underground which is causing the time field in the event to be set wrong and so it's never getting run. I've deployed a new version of the mtc server with a bunch of logging messages that will hopefully tell us if this happens again.

**Comment by tlatorre-uchicago** [comment]
I finally found this bug, and it has been fixed!
